### ISSUE TITLE
Problems compiling source

### ISSUE THREAD

**Issue by rthawkcom** [lowlander/dmx_usb_module#8]
make -C /lib/modules/5.15.0-46-generic/build  M=/home/dmx/dmx_usb_module
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-46-generic'
  CC [M]  /home/dmx/dmx_usb_module/dmx_usb.o
In file included from ./include/linux/kernel.h:19,
                 from /home/dmx/dmx_usb_module/dmx_usb.c:16:
/home/dmx/dmx_usb_module/dmx_usb.c: In function ‘dmx_usb_write’:
./include/linux/kern_levels.h:5:18: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
    5 | #define KERN_SOH "\001"  /* ASCII Start Of Header */
      |                  ^~~~~~
./include/linux/printk.h:422:11: note: in definition of macro ‘printk_index_wrap’
  422 |   _p_func(_fmt, ##__VA_ARGS__);    \
      |           ^~~~
/home/dmx/dmx_usb_module/dmx_usb.c:41:45: note: in expansion of macro ‘printk’
   41 | #define dbg(format, arg...) do { if (debug) printk(KERN_DEBUG __FILE__ ": " format "\n" , ## arg); } while (0)
      |                                             ^~~~~~
./include/linux/kern_levels.h:15:20: note: in expansion of macro ‘KERN_SOH’
   15 | #define KERN_DEBUG KERN_SOH "7" /* debug-level messages */
      |                    ^~~~~~~~
/home/dmx/dmx_usb_module/dmx_usb.c:41:52: note: in expansion of macro ‘KERN_DEBUG’
   41 | #define dbg(format, arg...) do { if (debug) printk(KERN_DEBUG __FILE__ ": " format "\n" , ## arg); } while (0)
      |                                                    ^~~~~~~~~~
/home/dmx/dmx_usb_module/dmx_usb.c:409:2: note: in expansion of macro ‘dbg’
  409 |  dbg("%s - minor %d, count = %d", __FUNCTION__, dev->minor, count);
      |  ^~~
  MODPOST /home/dmx/dmx_usb_module/Module.symvers
  CC [M]  /home/dmx/dmx_usb_module/dmx_usb.mod.o
  LD [M]  /home/dmx/dmx_usb_module/dmx_usb.ko
  BTF [M] /home/dmx/dmx_usb_module/dmx_usb.ko
Skipping BTF generation for /home/dmx/dmx_usb_module/dmx_usb.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-46-generic'
gcc -O2 -pipe -Wall dmx_usb_test.c -o dmx_usb_test

**Comment by lowlander** [comment]
@rthawkcom can you check if master fixes your problem ?
